# Generated by Django 5.0.6 on 2024-05-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('long_url', models.URLField()),
                ('no_clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
